### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by tiagoclc**
Corrects the peripherals initialization

### CODE REVIEW

**Review by dukeduck1984 — COMMENTED** [review]
those params are set to True by default

**Comment by tiagoclc** [comment]
without this my software hangs and doesnt wake and restart



________________________
Tiago C. Lima de Castro
+55 (21) 98577-5521<tel:+5521985775521>
Em Kaiyuan <notifications@github.com>, 11 de nov de 2019 1:19 PM escreveu:

@dukeduck1984 commented on this pull request.

those params are set to True by default

**Comment by dukeduck1984** [comment]
just out of curiousity, what's the version of the firmware?

I'm using esp32-20191003-v1.11-387-ga069340c1

**Comment by dukeduck1984** [comment]
I have set these params to True explicitly anyway to avoid any potential issues, also added garbage collection in the tilt angle measuring loop so that uftpd can be imported in the calibration mode without a reset.

**Comment by tiagoclc** [comment]
esp32-20191011-v1.11-422-g98c2eabaf.bin

____________________
Tiago C. Lima de Castro
+55 (21) 98577-5521


De: Kaiyuan <notifications@github.com>
Responder para: dukeduck1984/Hydrometer-Esp32-Micropython <reply@reply.github.com>
Data: segunda-feira, 11 de novembro de 2019 14:56
Para: dukeduck1984/Hydrometer-Esp32-Micropython <Hydrometer-Esp32-Micropython@noreply.github.com>
Cc: tiagoclc <tiagoclc@hotmail.com>, Author <author@noreply.github.com>
Assunto: Re: [dukeduck1984/Hydrometer-Esp32-Micropython] Update main.py (#6)


just out of curiousity, what's the version of the firmware?

I'm using esp32-20191003-v1.11-387-ga069340c1

**Pull request closed without merging**
